#-------------------------- MAIN INFORMATION --------------------------#
name: mortydex
description: "Mobile application for the Rick and Morty API"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#-------------------------- PRODUCTION PACKAGES --------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utilites
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  formz: ^0.8.0
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.0
  shared_preferences: ^2.1.0

  # Buisness logic
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  meta: ^1.15.0

  # Network
  retrofit: ^4.4.2
  dio: ^5.8.0+1

  # Icons
  flutter_svg: ^2.0.17

#-------------------------- DEVELOPMENT PACKAGES --------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7
  flutter_launcher_icons: ^0.14.3
  json_serializable: ^6.9.3


#-------------------------- LOCAL ASSETS --------------------------#
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icon/icon.png
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

 